# Generated by Django 3.2.14 on 2022-08-24 03:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient', '0001_initial'),
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid3, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('mobile', models.CharField(max_length=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('timeslot', models.CharField(choices=[('09.30 AM - 10.00 AM', '09.30 AM - 10.00 AM'), ('10.00 AM - 10.30 AM', '10.00 AM - 10.30 AM'), ('10.30 AM - 11.00 AM', '10.30 AM - 11.00 AM'), ('11.00 AM - 11.30 AM', '11.00 AM - 11.30 AM'), ('11.30 AM - 12.00 PM', '11.30 AM - 12.00 PM'), ('12.00 PM - 12.30 PM', '12.00 PM - 12.30 PM'), ('12.30 PM - 01.00 PM', '12.30 PM - 01.00 PM')], default='Select Time Slot', max_length=100)),
                ('consultant_type', models.CharField(choices=[('Physical Visit', 'Physical Visit'), ('Teleconsultation', 'Teleconsultation')], default='Select Type', max_length=100)),
                ('message', models.TextField()),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.consultant')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.department')),
                ('patient', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='patient.patient')),
            ],
        ),
    ]
